// tailwind.config.js — Design System Template
// Generated by refactor-design skill (based on Refactoring UI principles)
//
// How to use:
//   1. Copy this file to your project root as tailwind.config.js
//   2. Adjust the primary color hue (search "primary" below) to your brand
//   3. Set your font family in theme.fontFamily
//   4. Run `npx tailwindcss build` to generate your stylesheet
//
// All color values use HSL so hue shifts are easy — just change the first number.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,html,vue,svelte}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],

  theme: {
    // Override defaults where our scale is the whole story
    spacing: {
      '0':   '0px',
      'px':  '1px',
      '0.5': '0.125rem',   //  2px
      '1':   '0.25rem',    //  4px
      '1.5': '0.375rem',   //  6px
      '2':   '0.5rem',     //  8px
      '2.5': '0.625rem',   // 10px
      '3':   '0.75rem',    // 12px
      '3.5': '0.875rem',   // 14px
      '4':   '1rem',       // 16px
      '5':   '1.25rem',    // 20px
      '6':   '1.5rem',     // 24px
      '7':   '1.75rem',    // 28px
      '8':   '2rem',       // 32px
      '10':  '2.5rem',     // 40px
      '12':  '3rem',       // 48px
      '14':  '3.5rem',     // 56px
      '16':  '4rem',       // 64px
      '20':  '5rem',       // 80px
      '24':  '6rem',       // 96px
      '28':  '7rem',       // 112px
      '32':  '8rem',       // 128px
      '36':  '9rem',       // 144px
      '40':  '10rem',      // 160px
      '48':  '12rem',      // 192px
      '56':  '14rem',      // 224px
      '64':  '16rem',      // 256px
      '72':  '18rem',      // 288px
      '80':  '20rem',      // 320px
      '96':  '24rem',      // 384px
    },

    borderRadius: {
      'none': '0px',
      'sm':   '2px',
      DEFAULT:'4px',
      'md':   '6px',
      'lg':   '8px',
      'xl':   '12px',
      '2xl':  '16px',
      '3xl':  '24px',
      'full': '9999px',
    },

    fontSize: {
      'xs':   ['0.75rem',   { lineHeight: '1rem',    letterSpacing: '0em' }],
      'sm':   ['0.875rem',  { lineHeight: '1.25rem', letterSpacing: '0em' }],
      'base': ['1rem',      { lineHeight: '1.625rem',letterSpacing: '0em' }],
      'lg':   ['1.125rem',  { lineHeight: '1.75rem', letterSpacing: '0em' }],
      'xl':   ['1.25rem',   { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
      '2xl':  ['1.5rem',    { lineHeight: '2rem',    letterSpacing: '-0.01em' }],
      '3xl':  ['1.875rem',  { lineHeight: '2.25rem', letterSpacing: '-0.02em' }],
      '4xl':  ['2.25rem',   { lineHeight: '2.5rem',  letterSpacing: '-0.025em' }],
      '5xl':  ['3rem',      { lineHeight: '1.1',     letterSpacing: '-0.03em' }],
      '6xl':  ['3.75rem',   { lineHeight: '1.05',    letterSpacing: '-0.04em' }],
      '7xl':  ['4.5rem',    { lineHeight: '1',       letterSpacing: '-0.04em' }],
    },

    fontWeight: {
      thin:       '100',
      light:      '300',
      normal:     '400',
      medium:     '500',
      semibold:   '600',
      bold:       '700',
      extrabold:  '800',
      black:      '900',
    },

    letterSpacing: {
      tighter: '-0.05em',
      tight:   '-0.025em',
      normal:  '0em',
      wide:    '0.025em',
      wider:   '0.05em',
      widest:  '0.1em',
    },

    extend: {
      // ── Colors ─────────────────────────────────────────────────────────
      // Change the H value in hsl(H, S%, L%) to shift a whole palette.
      // Primary: 220 = blue. Try 260=violet, 142=green, 16=orange.
      colors: {
        primary: {
          50:  'hsl(220, 90%, 97%)',
          100: 'hsl(220, 82%, 91%)',
          200: 'hsl(220, 76%, 84%)',
          300: 'hsl(220, 72%, 73%)',
          400: 'hsl(220, 68%, 62%)',
          500: 'hsl(220, 70%, 50%)',
          600: 'hsl(220, 73%, 40%)',
          700: 'hsl(220, 76%, 31%)',
          800: 'hsl(220, 72%, 22%)',
          900: 'hsl(220, 68%, 15%)',
        },
        gray: {
          50:  'hsl(220, 14%, 96%)',
          100: 'hsl(220, 13%, 91%)',
          200: 'hsl(220, 12%, 84%)',
          300: 'hsl(220, 10%, 73%)',
          400: 'hsl(220,  8%, 60%)',
          500: 'hsl(220,  6%, 48%)',
          600: 'hsl(220,  8%, 38%)',
          700: 'hsl(220, 10%, 28%)',
          800: 'hsl(220, 13%, 18%)',
          900: 'hsl(220, 15%, 11%)',
        },
        green: {
          50:  'hsl(142, 76%, 96%)',
          100: 'hsl(142, 72%, 90%)',
          200: 'hsl(142, 68%, 81%)',
          300: 'hsl(142, 65%, 68%)',
          400: 'hsl(142, 63%, 54%)',
          500: 'hsl(142, 71%, 45%)',
          600: 'hsl(142, 76%, 36%)',
          700: 'hsl(142, 78%, 27%)',
          800: 'hsl(142, 75%, 18%)',
          900: 'hsl(142, 70%, 12%)',
        },
        red: {
          50:  'hsl(0, 86%, 97%)',
          100: 'hsl(0, 80%, 92%)',
          200: 'hsl(0, 76%, 83%)',
          300: 'hsl(0, 74%, 72%)',
          400: 'hsl(0, 72%, 62%)',
          500: 'hsl(0, 72%, 51%)',
          600: 'hsl(0, 74%, 41%)',
          700: 'hsl(0, 76%, 31%)',
          800: 'hsl(0, 74%, 21%)',
          900: 'hsl(0, 68%, 14%)',
        },
        amber: {
          50:  'hsl(38, 96%, 97%)',
          100: 'hsl(38, 94%, 91%)',
          200: 'hsl(38, 92%, 82%)',
          300: 'hsl(38, 90%, 70%)',
          400: 'hsl(38, 90%, 58%)',
          500: 'hsl(38, 92%, 50%)',
          600: 'hsl(35, 90%, 40%)',
          700: 'hsl(32, 88%, 32%)',
          800: 'hsl(30, 85%, 22%)',
          900: 'hsl(28, 80%, 15%)',
        },
      },

      // ── Font family ─────────────────────────────────────────────────────
      // Replace with your chosen font. Load from Google Fonts in <head>.
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        mono: [
          '"JetBrains Mono"',
          '"Fira Code"',
          '"Cascadia Code"',
          'Consolas',
          'monospace',
        ],
      },

      // ── Box shadows ──────────────────────────────────────────────────────
      // Elevation levels. Shadow color is dark navy (not pure black).
      boxShadow: {
        sm:    '0 1px 2px 0 hsl(220 40% 10% / 0.06)',
        DEFAULT: '0 1px 3px 0 hsl(220 40% 10% / 0.10), 0 1px 2px -1px hsl(220 40% 10% / 0.10)',
        md:    '0 4px 6px -1px hsl(220 40% 10% / 0.10), 0 2px 4px -2px hsl(220 40% 10% / 0.10)',
        lg:    '0 10px 15px -3px hsl(220 40% 10% / 0.10), 0 4px 6px -4px hsl(220 40% 10% / 0.10)',
        xl:    '0 20px 25px -5px hsl(220 40% 10% / 0.10), 0 8px 10px -6px hsl(220 40% 10% / 0.10)',
        '2xl': '0 25px 50px -12px hsl(220 40% 10% / 0.25)',
        inner: 'inset 0 2px 4px 0 hsl(220 40% 10% / 0.06)',
        none:  'none',
      },

      // ── Transition durations ─────────────────────────────────────────────
      transitionDuration: {
        '75':  '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
      },

      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        linear:  'linear',
        in:      'cubic-bezier(0.4, 0, 1, 1)',
        out:     'cubic-bezier(0, 0, 0.2, 1)',
        spring:  'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },

      // ── Max widths ────────────────────────────────────────────────────────
      maxWidth: {
        'prose': '65ch',
        'xs':    '20rem',   // 320px
        'sm':    '24rem',   // 384px
        'md':    '28rem',   // 448px
        'lg':    '32rem',   // 512px
        'xl':    '36rem',   // 576px
        '2xl':   '42rem',   // 672px
        '3xl':   '48rem',   // 768px
        '4xl':   '56rem',   // 896px
        '5xl':   '64rem',   // 1024px
        '6xl':   '72rem',   // 1152px
        '7xl':   '80rem',   // 1280px
        'full':  '100%',
      },
    },
  },

  plugins: [
    // Uncomment to add official Tailwind plugins:
    // require('@tailwindcss/forms'),
    // require('@tailwindcss/typography'),
    // require('@tailwindcss/aspect-ratio'),
  ],
};
